python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
    - requirements: docs/reinstall-cario-step-1.txt
    - requirements: docs/reinstall-cario-step-2.txt
  system_packages: false

mkdocs:
  configuration: mkdocs.yml
