name: Automations

on: [push, pull_request, pull_request_review, check_run, label]

jobs:
  run-sleuth-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://mrdonbrown/code-vide-generator:latest
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
